### ISSUE TITLE
[discovery] Explore and consolidate gray colors

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-tokens#1]
Need to consolidate the number of grays we support, whether that's aligning with Brand grays or our current web grays.

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/1890950/168896142-730ae8c5-0e4d-404a-8455-d8193d7b90f0.png">

Also, we don’t have a value for #8A8D90. Should we be supporting this?

[XD mockup](https://xd.adobe.com/view/067e136e-25a7-4e02-bcad-eef5e09471a9-532d/)

**Comment by bennypowers** [comment]
do we need to do anything here prior to 1.0?

**Comment by coreyvickery** [comment]
@markcaron Do you think we need to do any further research or stress testing of gray colors for this release?

**Comment by bennypowers** [comment]
Closed in #83
