### ISSUE TITLE
chore: bundle vsix plugin after release instead

### ISSUE THREAD

**Issue by eyevana** [RedHat-UX/red-hat-design-tokens#101]
The file name used in the VSCode (.vsix) plugin is bundle before token changes are released, so the plugin name is always behind the latest release version.

**Comment by bennypowers** [comment]
in `lib/release.js`, we should make sure that the `filename` variable is correct by comparing it to the `tag` parameter

**Comment by bennypowers** [comment]
@eyevana or @anujsingla either of you interested in picking this up?

**Comment by eyevana** [comment]
Yep, I can take this one.
