### ISSUE TITLE
Font family tokens produce unexpected results

### ISSUE THREAD

**Issue by zhawkins** [RedHat-UX/red-hat-design-tokens#113]
Using the fallback approach for multiple languages described here: https://red-hat-design-tokens.netlify.app/#font-family, you get different characters for non-Latin languages depending on which order you load your fallbacks:

This leads to the characters being incorrect on non-Latin language pages.

https://codepen.io/zackhawkins/pen/QWZeQWv

<img width="536" alt="image" src="https://github.com/RedHat-UX/red-hat-design-tokens/assets/2671663/2f896d64-986a-4e45-9c31-e2df03f910b6">

Maybe the best idea would be to have language specific `--rh-font-family-*` tokens?

**Comment by bennypowers** [comment]
cc @nikkimk

**Comment by zhawkins** [comment]
What's the haps on this one team? Can we chat about it? Maybe @nikkimk ?

**Comment by nikkimk** [comment]
@bennypowers @zhawkins can the three of us get together some morning? Or would this be a good office hours discussion? Would we need to modify our existing components to include language-specific tokens or can we just reset the default font-family tokens based on a parent's `lang` attr?

**Comment by zhawkins** [comment]
Yeah for sure. I can join the next office hours. I don't believe all sites use the same `lang` attr (though that work work for www.redhat.com).

**Comment by bennypowers** [comment]
Conclusions from office hours 2023-07-31:
- remove i18n fonts from existing tokens (so they'll be latin only)
- add script/lang specific tokens (e.g. hypothetically `--rh-font-family-body-text-ja`
- instruct page owners to set the family tokens to the language tokens on lang selectors e.g.
  ```html
  [lang^="ja"] {
    --rh-font-family-body-text: var(--rh-font-family-body-text-ja);
  }
  ```

**Comment by ryanaltvater** [comment]
@bennypowers @nikkimk I forgot to ask on our call this morning, but what would an ETA look like for the resolution discussed. I'm currently wrapping up converting `webrh` to consume design tokens, and would like to get an idea of when we can expect to go back in to update the fonts. Thanks! :)

**Comment by zeroedin** [comment]
Because this issue unfortunately results in a breaking change to the tokens package, we are going to have to defer the fix to a future release.  #139 will be sidelined for now until we can release this breaking change.

**Comment by zhawkins** [comment]
While I could see the _guidance_ as a breaking change, in that you're asking users to update their css, the actual _change_ fixes a breaking, hard to find, bug. 

IMO the change from the token output `RedHatText, "Red Hat Text", "Noto Sans Arabic", "Noto Sans Hebrew", "Noto Sans JP", "Noto Sans KR", "Noto Sans Malayalam"` to `RedHatText, "Red Hat Text"` is NOT a breaking change, it's fixing a bug.

**Comment by bennypowers** [comment]
the breaking part is that for arabic (for example), text would then render with the correct characters but not in the correct font

whereas for korean, it would fix the incorrect character rendering

**Comment by zhawkins** [comment]
I get that it would introduce a font change, but wouldn't it be better to fix the incorrect character rendering regardless of the font?
