### ISSUE TITLE
[task] Update new Brand colors in tokens

### ISSUE THREAD

**Issue by markcaron** [RedHat-UX/red-hat-design-tokens#117]
The DPO has updated our Brand colors. We'll need to update (and rename) our primitive colors.

<img width="510" alt="image" src="https://github.com/RedHat-UX/red-hat-design-tokens/assets/1890950/243bd4e9-7bbb-4014-868e-d264468068b7">
<img width="512" alt="image" src="https://github.com/RedHat-UX/red-hat-design-tokens/assets/1890950/52fda283-0ec2-4229-a2d3-586adf8b9972">
<img width="340" alt="image" src="https://github.com/RedHat-UX/red-hat-design-tokens/assets/1890950/731230eb-3e9a-403c-bf5e-c754b37969a1">

### Reds

- `red-70`: `#5F0000`
- `red-60`: `#A60000`
- `red-50`: `#EE0000`
- `red-40`: `#F56E6E`
- `red-30`: `#F9A8A8`
- `red-20`: `#FBC5C5`
- `red-10`: `#FCE3E3`

### Errors
Note: still some potential debate about naming these `error` as opposed to using a less semantic word

- `error-70`: `#731F00`
- `error-60`: `#B1380B`
- `error-50`: `#F0561D`
- `error-40`: `#F4784A`
- `error-30`: `#F89B78`
- `error-20`: `#FBBEA8`
- `error-10`: `#FFE3D9`

### Oranges

- `orange-70`: `#732E00`
- `orange-60`: `#9E4A06`
- `orange-50`: `#CA6C0F`
- `orange-40`: `#F5921B`
- `orange-30`: `#F8AE54`
- `orange-20`: `#FCCB8F`
- `orange-10`: `#FFE8CC`

### Yellows

- `yellow-70`: `#73480B`
- `yellow-60`: `#96640F`
- `yellow-50`: `#B98412`
- `yellow-40`: `#DCA614`
- `yellow-30`: `#FFCC17`
- `yellow-20`: `#FFE072`
- `yellow-10`: `#FFF4CC`

### Greens

- `green-70`: `#204D00`
- `green-60`: `#3D7317`
- `green-50`: `#63993D`
- `green-40`: `#87BB62`
- `green-30`: `#AFDC8F`
- `green-20`: `#D1F1BB`
- `green-10`: `#E9F7DF`

### Teals

- `teal-70`: `#004D4D`
- `teal-60`: `#147878`
- `teal-50`: `#37A3A3`
- `teal-40`: `#63BDBD`
- `teal-30`: `#9AD8D8`
- `teal-20`: `#B9E5E5`
- `teal-10`: `#DAF2F2`

### Blues

- `blue-70`: `#003366`
- `blue-60`: `#004D99`
- `blue-50`: `#0066CC`
- `blue-40`: `#4394E5`
- `blue-30`: `#92C5F9`
- `blue-20`: `#B9DAFC`
- `blue-10`: `#E0F0FF`

### Purples

- `purple-70`: `#21134D`
- `purple-60`: `#3D2785`
- `purple-50`: `#5E40BE`
- `purple-40`: `#876FD4`
- `purple-30`: `#B6A6E9`
- `purple-20`: `#D0C5F4`
- `purple-10`: `#ECE6FF`

**Comment by markcaron** [comment]
@bennypowers with the renaming of the colors from `100s` to `10s`, this might be a breaking change. Please advise.

**Comment by marionnegp** [comment]
@markcaron @coreyvickery, I think this will have to happen before we can finalize variables in Figma. Happy to help if you'd like.

**Comment by marionnegp** [comment]
@coreyvickery
- Are the secondary link colors ready to add? Not sure because all of the light theme tokens use the same gray.
- Should the destructive border theme colors be switched? The darker shade of red-orange is in the dark theme.
- Is there a semantic name for `red-40` in the Brand red group?

@bennypowers 
- The token name for a secondary link color starts `rh-color-**link**-secondary`. Should secondary link color tokens be added to a separate yaml file from the interactive color tokens (e.g., `rh-color-**interactive**-primary-default-on-light`) because the naming structure is different?

**Comment by bennypowers** [comment]
I'd suggest dropping the `link` name in favor of `interactive`
