### ISSUE TITLE
[feat] Use px units for everything but font specific properties.

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-tokens#20]
To make it easier to ensure layouts are 1:1  from design to development, we are adopting `px` as the standard unit for all values that are NOT font specific.

## Font specific properties

- font-size: rem
- line-height: rem (should this be rem?)

## Possible issues

Some of our current components are `em` based units.  This was done for two reasons:

1. Sites that override the root font-size, polluting `rem` values.  red hat dot com is an example of this. (note: the new Drupal 9 site has fixed this `D9 = 100% / 1rem / 16px`).
2. Relative units scale the layouts in relation to the font-sizes.

Therefore, some of our components will need to altered to move from `em` based to `px` based units.

## Possible accommodations

We *could* possibly have a utility that converts tokens from px to em or rems based on the developers needs.

**Comment by heyMP** [comment]
I initially had marked this as a feature request but changed it to discussion.  I'm of two minds; my gut tells me that moving to `px` will make our lives easier and make our components more bulletproof when integrating into other sites.  However, I do think that it might still be the most "responsive" to use relative units.  `rh-secondary-nav` is a good example of this.  It looks like the mockups no matter what font setting the user makes.

If I had to make the call I would say let's go with `px` values for everything but font-size properties but I could be swayed.  I.... don't know. lol 🤷‍♂️ 🤦‍♂️

**Comment by bennypowers** [comment]
see also https://github.com/RedHat-UX/red-hat-design-system/pull/489

**Comment by heyMP** [comment]
Course of action suggestion is that we make the change to `px` values now and then wait until RHDC upgrades to Drupal 9 to discuss whether or not they should be changed to `rem` to support a11y based layout scaling.

**Comment by bennypowers** [comment]
don't forget the changeset when making the pr

**Comment by bennypowers** [comment]
Closed by #22
