### ISSUE TITLE
[tool] Add Github action for publishing VScode extension 

### ISSUE THREAD

**Issue by heyMP** [RedHat-UX/red-hat-design-tokens#9]
To publish our token snippets to VScode we have to use Microsofts the `vsce` CLI.
https://code.visualstudio.com/api/working-with-extensions/publishing-extension

There is a Github Action that makes this process automated:
https://github.com/marketplace/actions/github-action-for-vsce

It looks like some devs for `access.redhat.com` are already publishing under the Red Hat certified account.  We should reach out and see if they can give us a publishing token.
https://marketplace.visualstudio.com/publishers/redhat

**Comment by bennypowers** [comment]
Thanks for opening this issue. I put in some thought around it this morning as well

I thought a first step could be to attach the `.vsix` file to GitHub releases. Experimenting with the CLI, it became clear that the npm `package.json` is not supposed to be the vscode package.json, [they are different manifest formats with different fields and validations)(https://github.com/microsoft/vscode-vsce/issues/655)

I'd like to grab this one:
1. remove vscode manifest stuff from package.json
2. generate a vs-code-non-npm package.json in `/editor` on build
3. generate and attach the `.vsix` file to GH releases


Subsequently, when we get a token, publish automatically in CI.

**Comment by bennypowers** [comment]
Update: did a little poking around and
- it's probably illegal to download vscode extension from M$' marketplace. is there an emoji for "dejected and exhausted"?
- We can direct neovim users to install our vscode snippets extention from git, then just call `lazy_load()` without specifiying `paths`, so long as the git repo we point to isn't the npm package but the vscode manifest. maybe that looks like this:
    ```lua
    use { 'redhat-ux/red-hat-design-tokens', branch = 'vscode-snippets' }
    ```
